runtime: python
env: flex

manual_scaling:
  instances: 1
  
runtime_config:
  python_version: 3
  


resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 10
                             
entrypoint: gunicorn -b :$PORT main:server 

# handlers:
#  - url: ./assets
#  static_dir: assets
  
# https://cloud.google.com/appengine/docs/standard/python/config/appref
env_variables:
  PKL_BUCKET:  'susano-dash.appspot.com' 